// Generated by Structorizer 3.30-06 

/**
 */
public class ue08_main
{



	/**
	 * @param args
	 */
	public static void main(String[] args)
	{
		// TODO: Check and accomplish variable declarations: 
		
		A:"UE08_Spannungsteiler;
		E:"R1: ";
		r1 == liefereEingabeWert;
		E:"R2: ";
		r2 == liefereEingabeWert;
		E:"Uein: ";
		ue == liefereEingabeWert;
		ua == ue * r2 / (r1 + r2);
		A:"Uaus = ";
		return 0;
	}

}
